"""Epic Seven gear optimization library."""

from e7_gear.combinator import (
    equip_optimizer_input,
    estimate_set_combination_count,
    final_gear_combos,
    gen_input_sets,
    gear_split,
    get_set_bonus,
    l2comb,
    l4comb,
    prepare_gear_combinations,
    set_combo,
    set_combination_iterate,
)
from e7_gear.io import (
    clean_up_dictionary_input,
    hero_json_to_df,
    item_json_to_df,
    startup_msg1,
    startup_msg2,
)
from e7_gear.optimizer import (
    HeroOptimizationResult,
    load_target_stats,
    optimize_hero,
    optimize_hero_from_template,
)
from e7_gear.recommender import prepare_hero_target, resolve_build, run_stat_reco, start_hero
from e7_gear.scoring import gear_stats, item_potential, verify_item_input, verify_main_stats
from e7_gear.settings import Settings, verify_settings
from e7_gear.stat_engine import (
    bonus_eqp_sum,
    enhance_mult,
    get_combo_stats,
    mainst_sum,
    pull_hero_stat_format,
    set_sum,
    subst_sum,
)
from e7_gear.tables import (
    gear_rating_lookup,
    gear_tier,
    grl,
    l2,
    l4,
    set_2,
    set_4,
    set_df,
    subs_cols,
    type_df,
)

__all__ = [
    "HeroOptimizationResult",
    "Settings",
    "bonus_eqp_sum",
    "clean_up_dictionary_input",
    "enhance_mult",
    "equip_optimizer_input",
    "estimate_set_combination_count",
    "final_gear_combos",
    "gear_rating_lookup",
    "gear_split",
    "gear_stats",
    "gear_tier",
    "gen_input_sets",
    "get_combo_stats",
    "get_set_bonus",
    "grl",
    "hero_json_to_df",
    "item_json_to_df",
    "item_potential",
    "l2",
    "l2comb",
    "l4",
    "l4comb",
    "load_target_stats",
    "mainst_sum",
    "optimize_hero",
    "optimize_hero_from_template",
    "prepare_gear_combinations",
    "prepare_hero_target",
    "pull_hero_stat_format",
    "resolve_build",
    "run_stat_reco",
    "set_2",
    "set_4",
    "set_combo",
    "set_combination_iterate",
    "set_df",
    "set_sum",
    "start_hero",
    "startup_msg1",
    "startup_msg2",
    "subst_sum",
    "subs_cols",
    "type_df",
    "verify_item_input",
    "verify_main_stats",
    "verify_settings",
]
